sudo: required
language: elixir
elixir:
  - 1.10
otp_release:
  - 23.0.2

addons: 
  postgres: '9.4'

services:
  - postgresql

script:
  - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
  - mix test && git push -f gigalixir HEAD:refs/heads/main
  