sudo: required
language: elixir
elixir:
  - 1.10
otp_release:
  - 23.0.2

addons: 
  postgres: '9.4'

services:
  - postgresql

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: script
  addons:
    apt:
      packages:
        - "python3"
        - "python3-pip"
  script:
    - python -VV
    - pip -V
    - pip3 -V
    - python3 -m pip install awscli 
    - bash ./deploy.sh
  on: 
    branch: master