sudo: required
language: elixir
elixir:
  - 1.10
otp_release:
  - 23.0.2

addons: 
  postgres: '9.4'

services:
  - postgresql

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on: 
    branch: main
  