sudo: required
language: elixir
elixir:
  - 1.10
otp_release:
  - 23.0.2

addons: 
  postgres: '9.4'

services:
  - postgresql

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
python: 3
addons:
  apt:
    update: true
    packages:
      - python3-pip
before_install:
  - which pip3    || echo 'which pip3 command failed.'
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip # not pip3
  - which pip3    || echo 'which pip3 command failed.'
cache:
  packages: true
  pip: true
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on: 
    branch: master
  